### ISSUE TITLE
Password less authentification

### ISSUE THREAD

**Issue by obsidienne** [danschultzer/pow_assent#10]
Hi,

Is it possible to create a provider to manage a password less authentification :
- https://github.com/zanderxyz/veil
- https://dennisreimann.de/articles/phoenix-passwordless-authentication-magic-link.html
- https://auth0.com/blog/is-passwordless-authentication-more-secure-than-passwords/

Is there any technical limitation in pow to create it ?

**Comment by danschultzer** [comment]
There's no technical limitation to build this with Pow. I don't think it would work as a provider for PowAssent, but it's trivial to set up with Pow itself. It would work pretty well as it's own custom pow extension.

The tutorial you posted (https://dennisreimann.de/articles/phoenix-passwordless-authentication-magic-link.html) is basically what you would need to do.

Here's a few pointers:

1. You'll use a custom changeset similar to PowAssent to not require password in registration: https://github.com/danschultzer/pow_assent/blob/master/lib/pow_assent/ecto/schema.ex#L62-L75

2. This is how user sessions are created: https://github.com/danschultzer/pow_assent/blob/master/lib/pow_assent/plug.ex#L58-L68

3. You can use the cache backend to store the tokens rather than having them in the database. They are transient like session id, so I don't see a reason for storing them in the DB. In the PowEmailConfirmation extension you can see how the store is used: https://github.com/danschultzer/pow/blob/master/lib/extensions/reset_password/plug.ex#L55-L63

How you actually implement it depends on your use case. Pow is build so you can take every single part out of it and use it independently. It's very easy to build your own custom registration and session controllers, only using the few parts you need from Pow. Alternatively, you can also build it as a whole extension like PowAssent.

**Comment by danschultzer** [comment]
I assume this answered your question? I'll close this issue for now 😄

**Comment by obsidienne** [comment]
Hi,

Yes, your answer is complete. Thanks. 
I want to remove my specific auth code, I need to find time to create a PR for pow, when the code is ready

Thanks
